; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_port = /dev/ttyACM0
upload_port = /dev/ttyACM0
extra_scripts = pre:gen_compile_commands.py
lib_deps = 
	simplefoc/SimpleFOCDrivers@^1.0.9
	simplefoc/SimpleDCMotor@^1.0.3
    ESP32Async/AsyncTCP@^3.3.2
